package me.amarantuss.roomapp.util.enums;

public enum PacketType {
    LOGIN,CREATE_ROOM,JOIN,EXCEPTION,SUCCESS,CLIENT_MESSAGE,SERVER_MESSAGE,LEAVE,CLOSE_ROOM,LOCK_ROOM,ROOM_BROADCAST,KICK,BAN,SET_ADMIN,STATUS,STATUS_REQUEST
}
